### ISSUE TITLE
documentation "issue"

### ISSUE THREAD

**Issue by ghost** [jsxc/ejabberd-cloud-auth#88]
hi, 2 years ago i raised bug #61 where i mentioned that external_cloud.sh (not in the deb package) should be xcauth.sh (also not in the deb package ..currently)

now i need to recreate my setup which used to work on ubuntu 18.04 but is failing now on 20.04.. how is it supposed to work now?

content of the xcauth package
```
 dpkg --listfiles xcauth
/.
/etc
/etc/ejabberd
/etc/ejabberd/dhparams.pem-xcauth-example
/etc/ejabberd/ejabberd.yml-xcauth-example
/etc/logrotate.d
/etc/logrotate.d/xcauth
/etc/sudoers.d
/etc/sudoers.d/xcauth
/etc/systemd
/etc/systemd/system
/etc/systemd/system/xcauth.service
/etc/systemd/system/xcejabberd.socket
/etc/systemd/system/xcpostfix.socket
/etc/systemd/system/xcprosody.socket
/etc/systemd/system/xcsaslauth.socket
/etc/xcauth.conf
/usr
/usr/lib
/usr/lib/prosody
/usr/lib/prosody/modules
/usr/lib/prosody/modules/xcauth
/usr/lib/prosody/modules/xcauth/mod_auth_external.lua-xcauth-version
/usr/lib/prosody/modules/xcauth/pseudolpty.lib.lua
/usr/lib/python3
/usr/lib/python3/dist-packages
/usr/lib/python3/dist-packages/xclib
/usr/lib/python3/dist-packages/xclib/__init__.py
/usr/lib/python3/dist-packages/xclib/auth.py
/usr/lib/python3/dist-packages/xclib/authops.py
/usr/lib/python3/dist-packages/xclib/check.py
/usr/lib/python3/dist-packages/xclib/configuration.py
/usr/lib/python3/dist-packages/xclib/db.py
/usr/lib/python3/dist-packages/xclib/dbmops.py
/usr/lib/python3/dist-packages/xclib/ejabberd_io.py
/usr/lib/python3/dist-packages/xclib/ejabberdctl.py
/usr/lib/python3/dist-packages/xclib/isuser.py
/usr/lib/python3/dist-packages/xclib/postfix_io.py
/usr/lib/python3/dist-packages/xclib/prosody_io.py
/usr/lib/python3/dist-packages/xclib/roster.py
/usr/lib/python3/dist-packages/xclib/roster_thread.py
/usr/lib/python3/dist-packages/xclib/saslauthd_io.py
/usr/lib/python3/dist-packages/xclib/sigcloud.py
/usr/lib/python3/dist-packages/xclib/sockact.py
/usr/lib/python3/dist-packages/xclib/utf8.py
/usr/lib/python3/dist-packages/xclib/version.py
/usr/sbin
/usr/sbin/xcauth
/usr/sbin/xcdelgroup
/usr/sbin/xcdelhost
/usr/sbin/xcdeluser
/usr/sbin/xcejabberdctl
/usr/sbin/xcrefreshroster
/usr/sbin/xcrestart
/usr/share
/usr/share/doc
/usr/share/doc/xcauth
/usr/share/doc/xcauth/CHANGELOG.md.gz
/usr/share/doc/xcauth/Cache.md
/usr/share/doc/xcauth/Database.md.gz
/usr/share/doc/xcauth/Installation.md.gz
/usr/share/doc/xcauth/LICENSE
/usr/share/doc/xcauth/Protocol.md
/usr/share/doc/xcauth/QuickInstallEjabberd.md
/usr/share/doc/xcauth/QuickInstallProsody.md
/usr/share/doc/xcauth/README.md
/usr/share/doc/xcauth/SystemDiagram.svg
/usr/share/doc/xcauth/Systemd.md.gz
/usr/share/doc/xcauth/Testing.md
/usr/share/doc/xcauth/changelog.Debian.gz
/usr/share/doc/xcauth/copyright
/var
/var/lib
/var/lib/xcauth
/var/log
/var/log/xcauth
```
the deb package does not even contain xcauth.py (xcauth seems to handle the query but fails on empty sqlite db - how should i create (basic structure) one which is not empty?
```
sudo xcauth -A user example.com 'blablabla' -u https://blablabla/index.php/apps/ojsxc/ajax/externalApi.php -s blablabla
2021-01-02 09:07:01,310 DEBUG: Start external auth script 2.0.3+ for ejabberd with endpoint: https://example.com/index.php/apps/ojsxc/ajax/externalApi.php
2021-01-02 09:07:01,311 DEBUG: Opening database connections main=/var/lib/xcauth/xcauth.sqlite3, cache=memory
2021-01-02 09:07:01,312 DEBUG: Creating cache table in <xclib.db.sq3c_debugger object at 0x7fb844808260>
Traceback (most recent call last):
  File "/usr/sbin/xcauth", line 17, in <module>
    perform(args)
  File "/usr/lib/python3/dist-packages/xclib/authops.py", line 86, in perform
    sc = sigcloud(xc, args.auth_test[0], args.auth_test[1], args.auth_test[2])
  File "/usr/lib/python3/dist-packages/xclib/sigcloud.py", line 18, in __init__
    self.secret, self.url, self.authDomain = ctx.per_domain(domain)
  File "/usr/lib/python3/dist-packages/xclib/__init__.py", line 46, in per_domain
    for row in self.db.conn.execute('SELECT authsecret, authurl, authdomain FROM domains WHERE xmppdomain = ?', (dom,)):
sqlite3.OperationalError: no such table: domains
```

**Comment by ghost** [comment]
I tried again, this time i tried blob/master/doc/Installation.md and installed the software via git+make install
the Installation.md contains
extauth_program: "/opt/xmpp-cloud-auth/xcauth.sh"
but you removed the xcauth.sh in 46b14fb588b4d8ac4a8b9166511acf268c8893ba

**Comment by ghost** [comment]
so extauth_program: socket is way to go, but it first needs few sockets to be enabled:
systemctl enable xcauth.service
systemctl start xcejabberd.socket

I will try to put this in my version of installation process and make it into a pull request.
